### ISSUE TITLE
React: Passing props to a Feature App

### ISSUE THREAD

**Issue by clebert** [sinnerschrader/feature-hub#179]
In addition to config feature apps that appear on a page multiple times (with different id specifiers) need to be able to accept props to be configured differently.

- A new property `instanceConfig` is added to `FeatureAppEnvironment`.
- A same new prop is added to the ReactFeatureAppContainer and `ReactFeatureAppLoader`.
- This prop is passed down to `createFeatureAppScope` and injected into the environment.

### Tasks

- [x] A new property `instanceConfig` is added to `FeatureAppEnvironment`. #350
- [x] A same new prop is added to the ReactFeatureAppContainer and `ReactFeatureAppLoader`. #350
- [x] Implement logic in `FeatureAppManager` #350
- [x] Documentation #355
  - When to use `instanceConfig` vs a Feature Service
- [x] JSDoc #350
