### ISSUE TITLE
Web Components: Add `@feature-hub/dom` package

### ISSUE THREAD

**Issue by clebert** [sinnerschrader/feature-hub#228]
We should offer an alternative implementation for integrators who do not want to use React.
The introduction of the website should be adapted accordingly, so that the focus is no longer on React.

For this we build a `FeatureAppLoader` custom element that loads a ´FeatureAppDefinition´ from the provided src url and a `FeatureAppContainer` custom element that provides loaded FeatureApps with a div rendered inside a shadow root. This ensures API compatibility to React `DomFeatureApp`s.
For destroying the feature app scope we utilize the custom elements lifecycle method.

The `FeatureApp` interface in this loader is named `DomFeatureApp`.
The `FeatureAppLoader` is able to pass instance props to the feature app instance.

### Tasks

- [x] add new package `@feature-hub/dom`
- [x] implement the `FeatureAppLoader`
- [x] implement `FeatureAppContainer`
- [x] new dom-integrator demo
- [x] documentation
- [x] JSDoc
