### ISSUE TITLE
Core: Add `ExternalsValidator` class

### ISSUE THREAD

**Issue by clebert** [sinnerschrader/feature-hub#240]
To keep our promise of failing early on incompatible FeatureApp combinations we want to provide an externals validator. This validator is instantiated with a map of external versions by the integrator and validates dependencies on those externals for consumers. These `externalDependencies` are declared in the consumer definition.

Provisioning the externals itself is not the responsibility of this class but of the integrator.

This class should be passed by the integrator into the `FeatureAppManager` and into the `FeatureServiceRegistry`.

Dependency versions are defined in semver notation and validated accordingly.

```js
{
  dependencies: {
    featureServices: {
      's2:history': '^1.0'
    },
    externals: {
      react: '^16.2'
    }
  },

  optionalDependencies: {
    featureServices: {
      's2:history': '^1.0'
    }
  }
}
```

All consumer definition keys mentioned above are (deep) optional.

There are 2 ways a validation could fail. A missing dependency and a dependency version mismatch. In both of those cases FeatureApp instantiation should fail with an error. If the consumer is a FeatureService those cases should lead to a warning and the dismissal of the service registration.

### Tasks

- [x] Change dependency declaration API to add the `featureServices` key. #314
  - [x] Adapt all mono repo consumers to the new api
- [x] Implement `ExternalsValidator`class #321
  - [x] Implement `validate(externals)` method
- [x] Use the `ExternalsValidator` in `FeatureServiceRegistry` #329
- [x] Use the `ExternalsValidator` in `FeatureAppManager` #329
- [x] Integrate `ExternalsValidator` in amd module loader demo #329
- [x] Documentation #340 #347 
- [x] JSDoc #339
