### ISSUE TITLE
React: Add a Feature Hub React context provider/consumer

### ISSUE THREAD

**Issue by fahrradflucht** [sinnerschrader/feature-hub#246]
Provides:

- Feature App manager singleton (`featureAppManager`)
- (optionally) Async SSR Manager (`asyncSsrManager`)

The context provider must receive its value from the integrator.

```jsx
<FeatureHubProvider value={{featureAppManager, asyncSsrManager}}>
  <FeatureAppLoader src="foo" serverSrc="bar" idSpecifier="baz" />
</FeatureHubProvider>
```

The React context consumer must be integrated into the `FeatureAppContainer` as
well as `FeatureAppLoader`, and thus reducing their set of public props.

## Tasks

- [x] Implement a React context provider `FeatureHubProvider` #312
- [x] Integrate the context consumer inside the `FeatureAppContainer` #312
- [x] Integrate the context consumer inside the `FeatureAppLoader` #312
- [x] Write and adapt existing JSDocs of the `@feature-hub/react` package #315 
- [x] Write a new "Feature App in Feature App" demo #313 
- [x] Adapt all demos #312
- [x] Adapt documentation and examples
  - Adapt examples #318 
  - Documentation of the special case "Feature App in Feature App" #319
  - In this case, our `@feature-hub/react` package must be declared as external. #319

**Comment by fahrradflucht** [comment]
Feature App authors requested to also have access to the context consumer, to be able to render Feature Apps themselves.

**Comment by KingHenne** [comment]
@fahrradflucht I don’t think that’s different from what we planned on providing with this feature, is it?

**Comment by fahrradflucht** [comment]
@KingHenne I think so to. I just wanted to note that here so that we have that in mind when writing documentation. Because at least I thought about this as an integrator convenience feature but without it in place react feature apps have no way of rendering other feature apps (given no other channel is introduced to pass down the necessary entities).

**Comment by KingHenne** [comment]
Understood. As a second motivation for the documentation this comment is indeed helpful. It does not change the implementation though, as Feature Apps would just use the same consumer as the integrator would.
