### ISSUE TITLE
SSR: Implement `@feature-hub/async-ssr-manager` Feature Service

### ISSUE THREAD

**Issue by clebert** [sinnerschrader/feature-hub#25]
To enable server side rendering, a Async SSR Manager Feature Service needs to be created. Feature Apps that want to be server side rendered must have this new Feature Service as a dependency.

**Tasks**

- [x] Add "old" SSR code into Server renderer package
- [x] Improve tests using Jest fake timers
- [x] Rename `server-renderer` package to `async-ssr-manager` #243 
- [x] Handle a global render timeout (config)
- [x] Integrate Async SSR Manager into `FeatureAppLoader` #248 
- [x] Write an integration test #251 
- [x] Write documentation #272 
- [ ] Add JSDoc comments #274
- [ ] Remove "incomplete" notice from README #274
