### ISSUE TITLE
SSR: Implement general state serialization mechanism for `@feature-hub/async-ssr-manager` consumers

### ISSUE THREAD

**Issue by clebert** [sinnerschrader/feature-hub#26]
To handover the state created while server side rendering, the serialized state of all Consumers needs to be stored and provided by the integrator using the SerializedStateManager Feature Service.

An example would be the disclaimer service handing over the registered disclaimers to the client.

### Notes

- The integrator has a way to **securely** serialize all consumer states at the end of the server side rendering.
- Consumers can receive their state on the client to pick up where they left.
- The `SerializedStateManager` must accept (all) serialized consumer states when hydrating on the client.

### API

```js
interface SerializedStateManager {
  register(createSerializedState: () => string): void;
  getSerializedState(): string | undefined;
  
  createSerializedStates(): string;
  setSerializedStates(serializedStates: string): void;
}
```

### Tasks

- [x] create new package `@feature-hub/serialized-state-manager` #287
- [x] implement the feature service #290 
  - [x] class and definition
  - [x] uri encode serialized state in `createSerializedStates`
  - [x] uri decode serialized state in `setSerializedStates`
- [x] integrate state serialization / hydration into ssr demo #291 
- [x] add documentation to website #299
  - [x] enhance SSR guide
  - [x] add a link to the sidebar
- [x] write JSDOC comments #290
