### ISSUE TITLE
SSR: Preload Feature App modules before hydrating in the client

### ISSUE THREAD

**Issue by clebert** [sinnerschrader/feature-hub#27]
After rendering Feature Apps on the server the JS files of the Feature Apps that were rendered on the server need to be loaded before hydrating.

- The integrator collects Feature App URLs for hydration via the FeatureAppLoader who knows which Feature Apps have been rendered on the server. The FeatureAppLoader adds the URLs with a `addUrlForHydration` function that is provided via the `FeatureHubContext`.
- The set of URLs is serialized into the HTML document by the integrator.
- On the client the integrator loads the URLs from the HTML document and calls the `preloadFeatureApp` method of the `FeatureAppManager` for all URLs before hydrating.
- We need to document the known edge case, maybe in the FAQ.
  - When a server-rendered Feature App view requires additional JS chunks in the client (via code splitting), then we can't guarantee that hydrating works without visual impact.
- Not appearing anymore is "Warning: Did not expect server HTML to contain a..."

### Tasks

- [x] add `addUrlForHydration` to `FeatureHubContextValue` and `InternalFeatureAppLoader` interface #320
- [x] use `addUrlForHydration` in `FeatureAppLoader` #320
- [x] integrate preloading (fix hydration) into ssr demo #322
- [ ] documentation: adapt SSR guide #324 
- [x] write JSDOC comments #320
