### ISSUE TITLE
Core: Configurable Logger

### ISSUE THREAD

**Issue by fahrradflucht** [sinnerschrader/feature-hub#293]
Currently we access `console` directly. Let users provide a logger instead.

The `FeatureAppManager` and `FeatureServiceRegistry` need to accept an optional logger through their constructor options. This option must also be added to the `createFeatureHub` options.

To let Feature Services and Apps log through common infrastructure, we will provide a new Feature Service named `LoggerService`. This new Feature Service automatically prefixes consumer logs with consumer UIDs. The underlaying logger is provided via a Feature Service factory.

Both loggers need to implement the same interface defined in Core. We also provide a `ConsoleLogger` implementing this interface for easy adaption.

## Tasks

- [x] evaluate common loggers and pick a `Logger` interface
  - [pino](https://github.com/pinojs/pino/blob/master/docs/api.md#logger-instance) and [bunyan](https://github.com/trentm/node-bunyan#levels) define the levels/methods `trace`, `debug`, `info`, `warn`, `error`, and `fatal`
  - [log4js](https://github.com/log4js-node/log4js-node/blob/master/types/log4js.d.ts#L256-L264) defines the levels `ALL`, `MARK`, `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`, `FATAL`, and `OFF`
  - `console` has the methods `debug`, `error`, `info`, `log`, `trace`, and `warn` (among others like `time` etc.)
  - [npm](https://docs.npmjs.com/misc/config#loglevel) defines the levels `silent`, `error`, `warn`, `notice`, `http`, `timing`, `info`, `verbose`, and `silly`
  - [RFC 5424](https://tools.ietf.org/html/rfc5424#page-11) defines the levels `emerg`, `alert`, `crit`, `error`, `warning`, `notice`, `info`, and `debug`
- [x] ~create `ConsoleLogger` in `@feature-hub/core`~ #402
- [x] integrate `logger` option into `FeatureAppManager` #404
- [x] integrate `logger` option into `FeatureServiceRegistry` #404
- [x] integrate `logger` option into `createFeatureHub` #404
- [x] integrate `logger` option into `@feature-hub/dom` define functions #406 
- [x] add `logger` to `FeatureHubContextValue` and integrate into `@feature-hub/react` `FeatureAppLoader`/`FeatureAppContainer` #408 
- [x] create `LoggerService` #413
- [x] use `LoggerService` in `HistoryService` #414 
- [x] use `LoggerService` in `AsyncSsrManager` #415 
- [x] use `LoggerService` in `TodoManager` #417 
- [x] add "Custom Logging" demo #418 
- [x] add documentation, e.g. a "Custom Logging" guide #423
