### ISSUE TITLE
SSR: Reschedule rerender with consecutive promises

### ISSUE THREAD

**Issue by clebert** [sinnerschrader/feature-hub#294]
After a consumer has scheduled a rerender with a promise, it should be possible
for the consumer to await this promise and reschdule the rerender with a
consecutive promise. It makes sense to rename `rerenderAfter` to
`scheduleRerender`. Furthermore, the promise should be an optional argument, so
that Feature Services can easily schedule a rerender without having to wait for
any asynchronous operations.

We should recommend encapsulating the `scheduleRerender` mechanics at a single
point in the application, e.g. in a Redux middleware.

Example:

```js
async function fetchAndScheduleRerender(url) {
  const promise = fetch(url).then(res => res.json());

  asyncSsrManager.scheduleRerender(promise);

  return promise;
}

const data1 = await fetchAndScheduleRerender('example.com');
const data2 = await fetchAndScheduleRerender(`example.com/${data1.foo}`);
```

Invalid Usage Example:

```js
const data = await fetch('example.com').then(res => res.json());
asyncSsrManager.scheduleRerender();
```

## Tasks

- [x] Rename `rerenderAfter` method to `scheduleRerender` #335
- [x] Implement inner loop (aka. promise queue) to check for subsequent promises (until there are not more promises) before next render pass. #337
- ~Adapt SSR demo to use the above example fetch pattern~
  - ~Real world use case using a localhost JSON endpoint~
- [x] Adapt existing JSDocs #338 
- [x] Documentation #338 
  - Adapt existing "Server Side Rendering" guide and examples
  - Document the "good" and invalid usage example

**Comment by clebert** [comment]
We should discuss or execute the discussed renaming (#279) in the context of this story.
